// Config generation for `twig init`: renders a commented config.toml from
// the wizard's answers so the written file doubles as documentation.
package initwiz

import (
	"fmt"
	"strings"
)

// Answers is what the wizard collected.
type Answers struct {
	Roots   []string // absolute paths
	Editors []Editor // editors to add as openers and include in the default set
}

// Generate renders config.toml. Roots under home are written ~-relative
// for readability.
func Generate(home string, a Answers) string {
	var b strings.Builder
	b.WriteString("# twig user config — https://joshpadnick.com/twig/reference/config/\n")
	b.WriteString("# Generated by `twig init`.\n\n")

	b.WriteString("# Directories scanned when the current repo can't resolve a fragment.\n")
	b.WriteString("# Each root is checked at <root>/*, <root>/*/*, and the Claude Code\n")
	b.WriteString("# worktree patterns. Conductor (~/conductor/workspaces) needs no root —\n")
	b.WriteString("# its provider covers it.\n")
	if len(a.Roots) == 0 {
		b.WriteString("roots = []\n")
	} else {
		b.WriteString("roots = [\n")
		for _, r := range a.Roots {
			fmt.Fprintf(&b, "  %q,\n", tildify(home, r))
		}
		b.WriteString("]\n")
	}

	b.WriteString("\n[open]\n")
	b.WriteString("# The opener set run on entry. \"ghostty\" is built in.\n")
	defaults := []string{`"ghostty"`}
	for _, e := range a.Editors {
		defaults = append(defaults, fmt.Sprintf("%q", e.Name))
	}
	fmt.Fprintf(&b, "default = [%s]\n", strings.Join(defaults, ", "))
	for _, e := range a.Editors {
		fmt.Fprintf(&b, "\n[open.openers.%s]\nkind = \"command\"\ncommand = %q\n", e.Name, e.Command)
	}

	b.WriteString("\n# More examples:\n")
	b.WriteString("# [open.openers.dev-browser]\n")
	b.WriteString("# kind = \"command\"\n")
	b.WriteString("# command = \"open http://localhost:5173\"\n")
	b.WriteString("\n# [remote]\n")
	b.WriteString("# auto = true          # search remote branches automatically when nothing matches locally\n")
	b.WriteString("# auto_create = true   # fetch + create (or reuse) the worktree without a prompt (implies auto)\n")
	return b.String()
}

// tildify shortens a path under home to ~/… for the written config.
func tildify(home, p string) string {
	if rel, ok := strings.CutPrefix(p, home+"/"); ok {
		return "~/" + rel
	}
	return p
}
